projet_web_classique_musicienimagepage:
    path:    /musicien/image/{codeMusicien}
    defaults: { _controller: ProjetWebClassiqueBundle:Musician:image }
    requirements:
        codeMusicien: \d+




projet_web_classique_indexcompositeurpage:
    path:     /compositeurs/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Compositeur:index, page: 1 }
    requirements:
        page: \d+

projet_web_classique_compositeurpage:
    path:     /compositeur/{codeMusicien}
    defaults: { _controller: ProjetWebClassiqueBundle:Compositeur:view }
    requirements:
        codeMusicien: \d+

projet_web_classique_initialcompositeurpage:
    path:     /compositeurs/initial/{initial}/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Compositeur:initial, initial: A, page: 1 }
    requirements:
        initial: \S
        page: \d+

projet_web_classique_naissancecompositeurpage:
    path:     /compositeurs/naissance/{naissance}/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Compositeur:naissance, naissance: 1900, page: 1 }
    requirements:
        naissance: \d+
        page: \d+




projet_web_classique_indexinterpretepage:
    path:     /interpretes/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Interprete:index, page: 1 }
    requirements:
        page: \d+

projet_web_classique_interpretepage:
    path:     /interprete/{codeMusicien}
    defaults: { _controller: ProjetWebClassiqueBundle:Interprete:view }
    requirements:
        codeMusicien: \d+

projet_web_classique_initialinterpretepage:
    path:     /interpretes/initial/{initial}/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Interprete:initial, initial: A, page: 1 }
    requirements:
        initial: \S
        page: \d+

projet_web_classique_naissanceinterpretepage:
    path:     /interpretes/naissance/{naissance}/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Interprete:naissance, naissance: 1900, page: 1 }
    requirements:
        naissance: \d+
        page: \d+





projet_web_classique_indexcheforchestrepage:
    path:     /cheforchestres/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:ChefDorchestre:index, page: 1 }
    requirements:
        page: \d+

projet_web_classique_cheforchestrepage:
    path:     /cheforchestre/{codeMusicien}
    defaults: { _controller: ProjetWebClassiqueBundle:ChefDorchestre:view }
    requirements:
        codeMusicien: \d+

projet_web_classique_initialcheforchestrepage:
    path:     /cheforchestres/initial/{initial}/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:ChefDorchestre:initial, initial: A, page: 1 }
    requirements:
        initial: \S
        page: \d+

projet_web_classique_naissancecheforchestrepage:
    path:     /cheforchestres/naissance/{naissance}/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:ChefDorchestre:naissance, naissance: 1900, page: 1 }
    requirements:
        naissance: \d+
        page: \d+





projet_web_classique_indexorchestrepage:
    path:     /orchestres/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Orchestres:index, page: 1 }
    requirements:
        page: \d+

projet_web_classique_orchestrepage:
    path:     /orchestre/{codeOrchestre}
    defaults: { _controller: ProjetWebClassiqueBundle:Orchestres:view }
    requirements:
        codeOrchestre: \d+

projet_web_classique_initialorchestrepage:
    path:     /orchestres/initial/{initial}/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Orchestres:initial, initial: A, page: 1 }
    requirements:
        initial: \S
        page: \d+




projet_web_classique_indexgenrepage:
    path:     /genres/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Genre:index, page: 1 }
    requirements:
        page: \d+

projet_web_classique_genrepage:
    path:     /genre/{codeGenre}
    defaults: { _controller: ProjetWebClassiqueBundle:Genre:view }
    requirements:
        codeGenre: \d+

projet_web_classique_initialgenrepage:
    path:     /genres/initial/{initial}/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Genre:initial, initial: A, page: 1 }
    requirements:
        initial: \S
        page: \d+




projet_web_classique_indexinstrumentpage:
    path:     /instruments/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Instrument:index, page: 1 }
    requirements:
        page: \d+

projet_web_classique_instrumentpage:
    path:     /instrument/{codeInstrument}
    defaults: { _controller: ProjetWebClassiqueBundle:Instrument:view }
    requirements:
        codeInstrument: \d+

projet_web_classique_initialinstrumentpage:
    path:     /instruments/initial/{initial}/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Instrument:initial, initial: A, page: 1 }
    requirements:
        initial: \S
        page: \d+

projet_web_classique_instrumentimagepage:
    path:     /instrument/image/{codeInstrument}
    defaults: { _controller: ProjetWebClassiqueBundle:Instrument:image }
    requirements:
        codeInstrument: \d+