projet_web_classique_musicienimagepage:
    path:    /musicien/image/{codeMusicien}
    defaults: { _controller: ProjetWebClassiqueBundle:Musician:image }
    requirements:
        codeMusicien: \d+




projet_web_classique_indexcompositeurpage:
    path:     /compositeurs/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Compositeur:index, page: 1 }
    requirements:
        page: \d+

projet_web_classique_compositeurpage:
    path:     /compositeur/{codeMusicien}
    defaults: { _controller: ProjetWebClassiqueBundle:Compositeur:view }
    requirements:
        codeMusicien: \d+

projet_web_classique_initialcompositeurpage:
    path:     /compositeurs/initial/{initial}/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Compositeur:initial, initial: A, page: 1 }
    requirements:
        initial: \S
        page: \d+

projet_web_classique_naissancecompositeurpage:
    path:     /compositeurs/naissance/{annee}/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Compositeur:naissance, annee: 1900, page: 1 }
    requirements:
        annee: \d+
        page: \d+




projet_web_classique_indexinterpretepage:
    path:     /interpretes
    defaults: { _controller: ProjetWebClassiqueBundle:Interprete:index }

projet_web_classique_interpretepage:
    path:     /interprete/{id}
    defaults: { _controller: ProjetWebClassiqueBundle:Interprete:view }
    requirements:
        id: \d+

projet_web_classique_initialinterpretepage:
    path:     /interpretes/initial/{initial}
    defaults: { _controller: ProjetWebClassiqueBundle:Interprete:initial, initial: A }
    requirements:
        initial: \S

projet_web_classique_naissanceinterpretepage:
    path:     /interpretes/naissance/{annee}
    defaults: { _controller: ProjetWebClassiqueBundle:Interprete:naissance, annee: 1900 }
    requirements:
        annee: \d+





projet_web_classique_indexcheforchestrepage:
    path:     /cheforchestres
    defaults: { _controller: ProjetWebClassiqueBundle:ChefDorchestre:index }

projet_web_classique_cheforchestrepage:
    path:     /cheforchestre/{id}
    defaults: { _controller: ProjetWebClassiqueBundle:ChefDorchestre:view }
    requirements:
        id: \d+

projet_web_classique_initialcheforchestrepage:
    path:     /cheforchestres/initial/{initial}
    defaults: { _controller: ProjetWebClassiqueBundle:ChefDorchestre:initial, initial: A }
    requirements:
        initial: \S

projet_web_classique_naissancecheforchestrepage:
    path:     /cheforchestres/naissance/{annee}
    defaults: { _controller: ProjetWebClassiqueBundle:ChefDorchestre:naissance, annee: 1900 }
    requirements:
        annee: \d+





projet_web_classique_albummusicien:
    path:    /album/musicien/{codeMusicien}/{page}
    defaults: { _controller: ProjetWebClassiqueBundle:Album:musicien, page: 1 }
    requirements:
        codeMusicien: \d+
        page: \d+