projet_web_home:
    resource: "@ProjetWebHomeBundle/Controller/"
    type:     annotation
    prefix:   /

projet_web_classique:
    resource: "@ProjetWebClassiqueBundle/Controller/"
    type:     annotation
    prefix:   /

anachardan_general:
    resource: "@AnachardanGeneralBundle/Controller/"
    type:     annotation
    prefix:   /

