projet_web_home:
    resource: "@ProjetWebHomeBundle/Controller/"
    type:     annotation
    prefix:   /

projet_web_classique:
    resource: "@ProjetWebClassiqueBundle/Controller/"
    type:     annotation
    prefix:   /

anachardan_general:
    resource: "@AnachardanGeneralBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: ProjetWebUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout