projet_web_home:
    resource: "@ProjetWebHomeBundle/Resources/config/routing.yml"
    prefix:   /

projet_web_classique:
    resource: "@ProjetWebClassiqueBundle/Resources/config/routing.yml"
    prefix:   /

anachardan_general:
    resource: "@AnachardanGeneralBundle/Controller/"
    type:     annotation
    prefix:   /

