# app/config/security.yml
security:
    encoders:
        ProjetWeb\ClassiqueBundle\Entity\Abonne: plaintext

    providers:
        main:
            entity: { class: ProjetWeb\ClassiqueBundle\Entity\Abonne, property: login }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        main:
            pattern: ^/
            form_login:
                provider: main
                login_path: login
                check_path: login_check
            anonymous: true

            logout:
                path: /logout
                target: /

            remember_me:
                key: "%secret%"
                lifetime: 2232000

    access_control:
            - { path: ^/private/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/private, roles: ROLE_ADMIN }
            - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }