Abonn„©:
    type: entity
    table: Abonn√©
    indexes:
        IDX_F72316A520B77BF2:
            columns:
                - Code_Pays
    uniqueConstraints:
        IX_Abonn√©:
            columns:
                - Nom_Abonn√©
                - Pr√©nom_Abonn√©
        IX_Abonn√©_1:
            columns:
                - Login
    id:
        codeAbonn„©:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Code_Abonn√©
            generator:
                strategy: IDENTITY
    fields:
        nomAbonn„©:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: Nom_Abonn√©
        pr„©nomAbonn„©:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: Pr√©nom_Abonn√©
        login:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: Login
        password:
            type: string
            nullable: true
            length: 10
            fixed: false
            column: Password
        adresse:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: Adresse
        ville:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: Ville
        codePostal:
            type: string
            nullable: true
            length: 50
            fixed: false
            column: Code_Postal
        email:
            type: string
            nullable: true
            length: 0
            fixed: false
            column: Email
        userid:
            type: string
            nullable: true
            length: 128
            fixed: false
            column: UserId
    manyToOne:
        codePays:
            targetEntity: Pays
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Code_Pays:
                    referencedColumnName: Code_Pays
            orphanRemoval: false
    lifecycleCallbacks: {  }
